### PR TITLE
Prevent opening new issues for eclipse.platform.releng repo

### PR DESCRIPTION
**Pull request by akurtakov**
As the repo has been merged into eclipse.platform.releng.aggregator one having new issues in this repo is plain confusing.

### CODE REVIEW

**Comment by akurtakov** [comment]
It's an effort to straighten issue reporting e.g. https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1695 had been reported to platform.releng repo at first and had to be transfered so the readme in the front page is not enough.
I'm not doing this at large (for all merge repos) as I would like to first see whether old issue will still be accessible with direct links but this is not an issue for releng repository if not.

**Review by pstankie — APPROVED** [review]
Looks good.

**Comment by pstankie** [comment]
Change has been applied.

**Comment by akurtakov** [comment]
Unfortunately, this makes links to old issues no longer accessible. @pstankie do you know of a way to only disable opening new issues but keep the old ones accessible? It's not for this repo but for other repos that would better not get new issues reported in.

**Comment by pstankie** [comment]
I'm not sure such option is available.

The workaround could be:
1. Reenable issues
2. Set blank_issues_enabled: false to config.yml file
3. Remove custom.md file.

That way the issue creation will be blocked.

More on this and customisation:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

**Pull request merged**
